"use strict";
let additionResult = 5 + 3;
console.log(additionResult);
let subtractionResult = 11 - 3;
console.log(subtractionResult);
let multiplicationResult = 4 * 2;
console.log(multiplicationResult);
;
let divisionResult = 16 / 2;
console.log(divisionResult);
